spring:
  profiles:
    active: renjian
  application:
    name: rj-web-api

---
spring:
  profiles: renjian
  datasource:
    druid:
      # 使用druid数据源
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 20
      max-active: 50
      max-wait: 60000
      min-idle: 1
      pool-prepared-statements: true
      filters: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        session-stat-enable: true
        profile-enable: true
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: 123456
        allow: 127.0.0.1
        deny:
  redis:
      cluster:
          # 各 Redis 节点信息
          nodes: 192.168.112.3:7001,192.168.112.3:7002,192.168.112.4:7001,192.168.112.4:7002,192.168.112.5:7001,192.168.112.5:7002
          # 执行命令超时时间
          command-timeout: 15000
          # 重试次数
          max-attempts: 5
          # 跨集群执行命令时要遵循的最大重定向数量
          max-redirects: 3
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 16
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
          # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
          test-on-borrow: true
server:
  port: 40113

#日志
logging:
  file: log/${spring.application.name}.log
  config: classpath:logback.xml

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://renjian:123456@localhost:40110/eureka/,http://renjian:123456@localhost:40111/eureka/


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.common.bean
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


