spring:
  profiles:
    active: renjian
  application:
    name: rj-zuul

---
spring:
  profiles: renjian
  datasource:
    druid:
      # 使用druid数据源
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 20
      max-active: 50
      max-wait: 60000
      min-idle: 1
      pool-prepared-statements: true
      filters: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        session-stat-enable: true
        profile-enable: true
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: 123456
        allow: 127.0.0.1
        deny:

server:
  port: 8081

logging:
  level:
    root: warn

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://renjian:123456@localhost:40110/eureka/,http://renjian:123456@localhost:40111/eureka/

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 10000
#  routes:
#    api-a:
#       path: /api/**
#       serviceId: rj-web-api
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#  max:
#  host:
#    connections: 500
#    socket-timeout-millis: 60000
#    connect-timeout-millis: 60000
#  routes:
#    spider-dataplatform-service-provider-greatwall.path: /api/**

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: bbd_z.search.domain
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30


